### ISSUE TITLE
Php 8 Compatibility

### ISSUE THREAD

**Issue by pascalf22** [ozh/phpass#4]
Hello ! 
Thanks a lot for PHPass ! 
I upgrade my PHP version to the version 8.

Does PHPass is compatible with PHP 8 ?
Thanks !
Pascal

**Comment by ozh** [comment]
I packaged this lib to use it with [YOURLS ](https://github.com/YOURLS/YOURLS) which is fully compatible with PHP 8 so I'd say yes :)

(I probably won't spend time updating tests here to be honest)

**Comment by pascalf22** [comment]
Ok thanks a lot for your response ! I tried it yesterday and it works perfectly with PHP 8.0.13

Thanks a lot !
